export const projects = [
  {
    id: 1,
    title: 'Extension Réseau HTA/BT — Settat',
    client: 'ONEE — Direction Régionale',
    region: 'Province de Settat',
    category: 'Distribution',
    year: '2023',
    budget: '4,2 M MAD',
    duration: '8 mois',
    bg: 'linear-gradient(135deg, #0a1628, #0d2040)',
    desc: "Extension et renforcement du réseau de distribution HTA 22 kV et BT dans la province de Settat. Comprend 42 km de lignes aériennes, 3 postes cabines et 680 branchements abonnés.",
    featured: true,
  },
  {
    id: 2,
    title: 'Éclairage Public — Bouskoura',
    client: 'Commune Urbaine de Bouskoura',
    region: 'Grand Casablanca-Settat',
    category: 'Éclairage',
    year: '2023',
    budget: '1,8 M MAD',
    duration: '5 mois',
    bg: 'linear-gradient(135deg, #003d7a, #005fa3)',
    desc: "Installation d'un réseau d'éclairage public LED sur les axes principaux de la commune. 380 candélabres, armoires de commande télégestionnées et réseau souterrain BT.",
    featured: false,
  },
  {
    id: 3,
    title: 'Centrale PV 500 kWp — Laâyoune',
    client: 'MASEN',
    region: 'Région Laâyoune-Sakia el Hamra',
    category: 'Solaire',
    year: '2022',
    budget: '7,5 M MAD',
    duration: '10 mois',
    bg: 'linear-gradient(135deg, #005fa3, #0079cc)',
    desc: "Réalisation d'une centrale photovoltaïque raccordée au réseau HTB. 1 420 panneaux bifaciaux, 2 onduleurs centraux, supervision SCADA et raccordement 22 kV.",
    featured: false,
  },
  {
    id: 4,
    title: 'Poste Source 60/22 kV — Kénitra',
    client: 'ONEE — Direction Nord',
    region: 'Région Rabat-Salé-Kénitra',
    category: 'Distribution',
    year: '2022',
    budget: '12,3 M MAD',
    duration: '14 mois',
    bg: 'linear-gradient(135deg, #0a1628, #162540)',
    desc: "Construction d'un poste source 60/22 kV pour le renforcement du réseau électrique de la région Kénitra. Deux transformateurs HTB 30 MVA, jeu de barres blindé et téléconduite.",
    featured: false,
  },
  {
    id: 5,
    title: 'Réseau BT + Éclairage — Mohammedia',
    client: 'Commune de Mohammedia',
    region: 'Grand Casablanca-Settat',
    category: 'Éclairage',
    year: '2022',
    budget: '2,1 M MAD',
    duration: '6 mois',
    bg: 'linear-gradient(135deg, #00467a, #005fa3)',
    desc: "Réhabilitation du réseau BT et remplacement de l'éclairage public vétuste par des solutions LED basse consommation. 520 points lumineux sur 14 km de voirie.",
    featured: false,
  },
  {
    id: 6,
    title: 'VRD Zone Industrielle — Berrechid',
    client: "Ministère de l'Équipement",
    region: 'Province de Berrechid',
    category: 'VRD',
    year: '2023',
    budget: '6,8 M MAD',
    duration: '11 mois',
    bg: 'linear-gradient(135deg, #0a1628, #0f1e35)',
    desc: "Réalisation des travaux VRD de la zone industrielle de Berrechid : voirie, réseau d'assainissement, éclairage et distribution électrique BT. Surface traitée : 18 ha.",
    featured: false,
  },
  {
    id: 7,
    title: 'Electrification Rurale — Khénifra',
    client: 'ONEE — Programme PERG',
    region: 'Région Béni Mellal-Khénifra',
    category: 'Distribution',
    year: '2021',
    budget: '3,4 M MAD',
    duration: '9 mois',
    bg: 'linear-gradient(135deg, #0a2040, #0d2850)',
    desc: "Electrification de 12 douars dans la province de Khénifra dans le cadre du PERG. 56 km de réseau HTA monophasé, 28 postes de distribution et 340 branchements.",
    featured: false,
  },
  {
    id: 8,
    title: 'PV Toiture 200 kWp — Agadir',
    client: 'Région Souss-Massa',
    region: 'Agadir-Ida Ou Tanane',
    category: 'Solaire',
    year: '2021',
    budget: '2,9 M MAD',
    duration: '4 mois',
    bg: 'linear-gradient(135deg, #004d8a, #0069be)',
    desc: "Installation de centrales PV en toiture sur 4 bâtiments administratifs régionaux. 580 panneaux, système de monitoring en temps réel et bilan carbone certifié.",
    featured: false,
  },
];